#!/usr/bin/env bash

cd ..

if [ -d info-center ]; then
	rm -rf ~/.local/share/gnome-shell/extensions/info-center@muzsij
	cp -r info-center ~/.local/share/gnome-shell/extensions/info-center@muzsij
	cd ~/.local/share/gnome-shell/extensions/info-center@muzsij/schemas
	glib-compile-schemas .
	gnome-session-quit --no-prompt
else
	echo "Extension folder not found"
fi
